logo_title: dadong 大东

style: black

favicon: /favicon.ico

#menu:
#  作品: /project
#  域名: /domain
#  友联: /links
#  关于: /about
#  Github: https://github.com/sanjinhub

# 做了域名限制，请改成自己的 KEY
valine:
  appId: iX4YvHeQeizhBc34Q7yTkHVf-gzGzoHsz
  appKey: Mys0COlqlCIbQVzgYJI30s4i

highlight:
  enable: false
